[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = upesy_wroom
framework = arduino
lib_compat_mode = strict
lib_ldf_mode = chain
monitor_speed = 115200


[env:MAIN_controller]
lib_deps =
    Adafruit LSM6DS
    adafruit/Adafruit BMP280 Library@^2.6.8 
    Utilities
build_src_filter = -<**/*.cpp> +<**/main-controller.cpp> 

[env:MAIN_drone]
lib_deps =
    Adafruit LSM6DS
    adafruit/Adafruit BMP280 Library@^2.6.8 
    Utilities
build_src_filter = -<**/*.cpp> +<**/main-drone.cpp> 

[env:TESTING_motors]
lib_deps =
    Adafruit LSM6DS
    adafruit/Adafruit BMP280 Library@^2.6.8 
    Peripherals
build_src_filter = -<**/*.cpp> +<**/test-motors.cpp> 


[env:TESTING_macAddress]
lib_deps =
    Adafruit LSM6DS
    adafruit/Adafruit BMP280 Library@^2.6.8 
build_src_filter = -<**/*.cpp> +<**/find-mac-address.cpp> 



